### ISSUE TITLE
Package request

### ISSUE THREAD

**Issue by mike-lischke** [netConnects/rich-web-platform#2]
Hi, @senthurai. I'm trying to get in contact with you for a request regarding one of your (actually unused) packages you published on npmjs.com. Please contact me at mike@lischke-online.de! Thanks.

PS: sorry for misusing this repository, but I could not find any contact information of you and the NetConnects website is non-functional.

**Comment by senthurai** [comment]
Hello, please let me what you want me to do..?

**Comment by mike-lischke** [comment]
Thanks for getting back to me! Continuing in private mail...
